services:
  # traineemanagement.api:
  #   image: traineemanagement.api:latest
  #   build:
  #     context: .
  #     dockerfile: TraineeManagement/Dockerfile
  #   ports:
  #     - "5001:8081"
  #   networks:
  #     - traineemanagement.api
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
      
  
  # trainingdirectory.api:
  #   image: trainingdirectory.api:latest
  #   build:
  #     context: .
  #     dockerfile: TrainingDirectory.Api/Dockerfile
  #   ports:
  #     - "5002:8082"
  #   networks:
  #     - trainingdirectory.api
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy

  # submissionprocessor.worker:
  #   image: submissionprocessor.worker:latest
  #   build:
  #     context: .
  #     dockerfile: SubmissionProcessor.Worker/Dockerfile
  #   ports:
  #     - "5003:8083"
  #   networks:
  #     - submissionprocessor.worker
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
      
    
    
  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_db}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
    # networks:
    #   - mysql
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: redis_cache
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    # networks:
    #   - redis
    volumes:
      - redis_data:/data
  
  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    # networks:
    #   - rabbitmq
    volumes:
      - rabbitmq_lib:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
 
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  
 
volumes:
  mysql_data:
  redis_data:
  rabbitmq_lib:
    driver: local
  rabbitmq_log:
    driver: local
